import PDFDocument from 'pdfkit'

/**
 * Generate a PDF complaint report for a road damage submission.
 * Returns a Buffer containing the PDF.
 */
export async function generateComplaintPDF(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' })
    const chunks = []

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const primaryColor = '#f97316'  // orange
    const darkColor = '#1e293b'
    const grayColor = '#64748b'

    // ── Header ──────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(darkColor)

    doc.fontSize(22).fillColor(primaryColor).text('RoadScan', 50, 22)
    doc.fontSize(10).fillColor('#ffffff').text('Road Damage Complaint Report', 50, 48)
    doc.fillColor('#94a3b8').text('Surat Municipal Corporation', 50, 60)

    doc.moveDown(3)

    // ── Tracking ID banner ───────────────────────────────────
    doc.rect(50, 100, doc.page.width - 100, 40).fill('#fff7ed')
    doc.fontSize(11).fillColor(grayColor).text('Tracking ID', 60, 108)
    doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold')
       .text(report.trackingId, 60, 120)
    doc.font('Helvetica')

    doc.moveDown(3)

    // ── Report details ───────────────────────────────────────
    const startY = 160
    const col1 = 50
    const col2 = 300

    function field(label, value, x, y) {
      doc.fontSize(9).fillColor(grayColor).text(label.toUpperCase(), x, y)
      doc.fontSize(11).fillColor(darkColor).text(value || '—', x, y + 14, { width: 220 })
    }

    field('Damage Type', formatDamageType(report.damageType), col1, startY)
    field('Status', report.status?.replace('_', ' ').toUpperCase(), col2, startY)

    field('Date Submitted', formatDate(report.createdAt), col1, startY + 55)
    field('AI Confidence', report.confidenceScore
      ? `${Math.round(report.confidenceScore * 100)}%`
      : 'Manual entry', col2, startY + 55)

    field('GPS Coordinates',
      `${report.coordinates.lat.toFixed(6)}, ${report.coordinates.lng.toFixed(6)}`,
      col1, startY + 110)

    if (report.address) {
      field('Location Address', report.address, col1, startY + 165)
    }

    if (report.description) {
      field('Description', report.description, col1, startY + 220)
    }

    // ── Divider ──────────────────────────────────────────────
    const divY = report.description ? startY + 290 : startY + 240
    doc.moveTo(50, divY).lineTo(doc.page.width - 50, divY)
       .strokeColor('#e2e8f0').lineWidth(1).stroke()

    // ── Notice ───────────────────────────────────────────────
    doc.fontSize(9).fillColor(grayColor)
       .text(
         'This complaint has been automatically generated by RoadScan and submitted to ' +
         'Surat Municipal Corporation. Please quote the Tracking ID for all follow-up enquiries.',
         50, divY + 15, { width: doc.page.width - 100 }
       )

    // ── Footer ───────────────────────────────────────────────
    doc.fontSize(8).fillColor('#94a3b8')
       .text(
         `Generated by RoadScan  •  ${new Date().toLocaleString('en-IN')}  •  roadscan.vercel.app`,
         50, doc.page.height - 40,
         { align: 'center', width: doc.page.width - 100 }
       )

    doc.end()
  })
}

function formatDamageType(type) {
  if (!type) return 'Unknown'
  return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}

function formatDate(dateStr) {
  if (!dateStr) return '—'
  return new Date(dateStr).toLocaleString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}
